apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    labels:
      app: portal
    name: portal
  spec:
    ports:
    - name: 443-tcp
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      app: portal
      deploymentconfig: portal
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    annotations:
    labels:
      app: portal
    name: portal
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: portal
      deploymentconfig: portal
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
  
        labels:
          app: portal
          deploymentconfig: portal
      spec:
        containers:
        - image: docker.riostox.com:5000/portal:riostox
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value:  "test"
            - name: EGG_SERVER_ENV
              value: "test"
          name: portal
          command: ["npm start"]
          ports:
          - containerPort: 443
            protocol: TCP
          resources:
            limits:
              cpu: "10"
              memory: 1Gi
            requests:
              cpu: "2"
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
kind: List
metadata: {}
